/*
 * generated by Xtext 2.25.0
 */
package com.coffeestorm.dsl.sheetmagic.validation;

import org.eclipse.xtext.validation.Check;

import com.coffeestorm.dsl.sheetmagic.sheetmagic.AreaMapping;
import com.coffeestorm.dsl.sheetmagic.sheetmagic.SheetmagicPackage;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class SheetmagicValidator extends AbstractSheetmagicValidator {
	
	@Check
	public void checkGreetingStartsWithCapital(AreaMapping mapping) {
		String startCol = mapping.getStartCol();
		if (startCol.matches("\\d+")) {
			// integer
			return; // OK
		}
		if (startCol.matches("[a-zA-Z]+")) {
			// letter column id
			return; // OK
		}
		error("Invalid column. Use Integer number index or letter index",
			SheetmagicPackage.Literals.AREA_MAPPING__START_COL);
	}
	
}
