/*
 * generated by Xtext 2.25.0
 */
package com.coffeestorm.dsl.sheetmagic.ide;


/**
 * Use this class to register ide components.
 */
public class SheetmagicIdeModule extends AbstractSheetmagicIdeModule {
}
