/*
 * generated by Xtext 2.25.0
 */
package com.coffeestorm.dsl.sheetmagic;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SheetmagicStandaloneSetup extends SheetmagicStandaloneSetupGenerated {

	public static void doSetup() {
		new SheetmagicStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
