/*
 * generated by Xtext 2.25.0
 */
package com.coffeestorm.dsl.sheetmagic.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SheetmagicUiModule extends AbstractSheetmagicUiModule {

	public SheetmagicUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
